# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7907d2787b1b87c77b4f7df3f12dd78f2fe8d640a62bb32a55585243c8850b15a0c20a412760f76ecc08ceb0cf8710de365f8facc648008d04b942fabb7a877c

test:
  secret_key_base: 5c7482a6ccb664e303b4d89db6d46638e6c685d0d6bcce48f29ccb7b2badde9644e514c20409c934316ad1de1ad2cdab6af071833472cfbb9d2c071aa0987209

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
